<a href="https://colab.research.google.com/github/yasrilimam98/sispako-flutter/blob/main/SPK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Library Numpy dan disimapan dalam nama 'np'
import numpy as np

# Membuat array 2d sesuai dengan matrix penyekalaan
init_matrix = np.array([[5,2,3,5,4,4], [4,4,4,4,4,4], [1,4,4,4,4,4], [4,1,2,3,3,2]])
# Cek hasil array 2d
print(init_matrix)

[[5 2 3 5 4 4]
 [4 4 4 4 4 4]
 [1 4 4 4 4 4]
 [4 1 2 3 3 2]]


In [ ]:
import math

def normalization(matrix):
    row_values = []
    norm_matrix = []
    
    for i in range(matrix.shape[0]): # Looping per baris (kriteria)
        # Menghitung sum tiap x_{ij}^2
        sum_row = sum([pow(x,2) for x in matrix[i]])
        
        for j in range(matrix[i].shape[0]): # Looping per kolom (alternatif)
            # membangi nilai asli x_{ij} dengan hasil akar
            r_value = matrix[i][j] / math.sqrt(sum_row)
            
            # Masukkan hasil normalisasi ke list tiap baris
            row_values.append(r_value)
        
        #Masukkan hasil normalisasi per baris ke matrix normalisasi
        norm_matrix.append(row_values)
        
        #Kosongkan list normalisasi perbaris
        row_values = []
            
    # Rturn matrix normalisasi dalam bentuk numpy array
    return np.asarray(norm_matrix)

In [ ]:
# Testing Fungsi Normalisasi
norm = normalization(init_matrix)
print(norm)

[[0.51298918 0.20519567 0.30779351 0.51298918 0.41039134 0.41039134]
 [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]
 [0.11111111 0.44444444 0.44444444 0.44444444 0.44444444 0.44444444]
 [0.60999428 0.15249857 0.30499714 0.45749571 0.45749571 0.30499714]]


In [ ]:
# Kalkulasi skor normalisasi terbobot

# Bobot untuk Kriteria C1, C2, C3, dan C4
c_weights = np.array([30,20,30,20])

# Fungsi untuk kalkulasi matrix terbobot. Paramter yang diperlukan adalah nilai ternormalisasi dan bobot
# Ingat! Kriteria adalah baris, Kolom adalah alternatif
def weighted_normalization(n_matrix, c_weights):
    # Buat salinan nilai ternormalisasi
    norm_weighted = n_matrix
    
    for i in range(c_weights.shape[0]): # Looping tiap kriteria
        # Kalkulasi normalisasi terbobot
        norm_weighted[i] = [r * c_weights[i] for r in norm_weighted[i]]
    
    return np.asarray(norm_weighted)

In [ ]:
# Testing Matrix Normalisasi terbobot
w_norm = weighted_normalization(norm, c_weights)
print(w_norm)

[[15.38967528  6.15587011  9.23380517 15.38967528 12.31174023 12.31174023]
 [ 8.16496581  8.16496581  8.16496581  8.16496581  8.16496581  8.16496581]
 [ 3.33333333 13.33333333 13.33333333 13.33333333 13.33333333 13.33333333]
 [12.19988563  3.04997141  6.09994281  9.14991422  9.14991422  6.09994281]]


In [ ]:
# Membuat label benefit dan cost untuk tiap kriteria
# Benefit = 1
# Cost = 0
c_label = np.array([1, 1, 1, 1])

In [ ]:
# Fungsi mencari solusi ideal positif dan negatif
# Parameter yang dibutuhkan adalah, matrix normalisasi terbobot dan label benefit cost untuk tiap kriteria

def ideal(w_norm, c_label):
    a_positif = []
    a_negatif = []
    
    for i in range(w_norm.shape[0]):
        if c_label[i] == 1:
            # Untuk ideal positif
            a_max = max(w_norm[i])
            a_positif.append(a_max)
            
            # Untuk ideal negatif
            a_min = min(w_norm[i])
            a_negatif.append(a_min)
        elif c_label[i] == 0:
            # Untuk ideal positif
            a_max = min(w_norm[i])
            a_positif.append(a_max)
            
            # Untuk ideal negatif
            a_min = max(w_norm[i])
            a_negatif.append(a_min)
    
    ideal_value = np.array([a_positif, a_negatif])
    
    # Return dalam bentuk transpose sehingga baris = kriteria, kolom = solusi ideal positif dan negatid
    return ideal_value.transpose()

In [ ]:
# Testing Solusi Ideal
ideal_v = ideal(w_norm, c_label)
print(ideal_v)

[[15.38967528  6.15587011]
 [ 8.16496581  8.16496581]
 [13.33333333  3.33333333]
 [12.19988563  3.04997141]]


In [ ]:
# Kalkulasi Jarak Ideal Positif dan Negatif
# Disini akan menggunakan bantuan fungsi `distance` dari library `scipy.spatial`
# Parameter :
# 1. Matrix normalisasi terbobot
# 2. Nilai solusi ideal positif dan negatif

from scipy.spatial import distance as d

def alt_ideal_distance(w_norm, ideal_v):
    d_positif = []
    d_negatif = []
    
    # Kalkulasi Jarak
    for i in range(w_norm[0].shape[0]):
        # positif
        dp = d.euclidean(w_norm[:,i], ideal_v[:,0])
        d_positif.append(dp)
        
        # negatif
        dn = d.euclidean(ideal_v[:,1], w_norm[:,i])
        d_negatif.append(dn)
    
    d_positif = np.asarray(d_positif)
    d_negatif = np.asarray(d_negatif)
    
    d_value = np.array([d_positif, d_negatif])
        
    return d_value.transpose()

In [ ]:
# Testing Jarak Ideal Positif
distance = alt_ideal_distance(w_norm, ideal_v)
print(distance)

[[10.         12.99938799]
 [12.99938799 10.        ]
 [ 8.66625866 10.8984407 ]
 [ 3.04997141 14.91551073]
 [ 4.33312933 13.23268828]
 [ 6.8324949  12.13247965]]


In [ ]:
# Kalkulsi skor akhir
# Parameter :
# 1. distance : matrix jarak solusi positif dan negatif. 
# Baris adalah kriteria, kolom adalah solusi ideal positif dan negatif

def final_rank(distance):
    v = []
    
    for i in range(distance.shape[0]):
        vi = distance[i][1] / (distance[i][1] + distance[i][0])
        v.append(vi)
    
    return np.asarray(v)

In [ ]:
# Testing skor akhir
ranking = final_rank(distance)
print(ranking)

[0.56520582 0.43479418 0.55704616 0.83023159 0.75332037 0.63973087]
